In [2]:
import pandas as pd

df = pd.read_csv("ds_salaries.csv")

df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [3]:
print(df.shape)

(607, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    object
 3   employment_type     607 non-null    object
 4   job_title           607 non-null    object
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    object
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    object
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    object
 11  company_size        607 non-null    object
dtypes: int64(5), object(7)
memory usage: 57.0+ KB

In [6]:
df = df.drop(columns=['Unnamed: 0'])

In [7]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [8]:
experience_map = {
    'EN': 'Entry Level',
    'MI': 'Mid Level',
    'SE': 'Senior Level',
    'EX': 'Executive Level'
}

df['experience_level'] = df['experience_level'].map(experience_map)

In [9]:
employment_map = {
    'FT': 'Full Time',
    'PT': 'Part Time',
    'CT': 'Contract',
    'FL': 'Freelance'
}

df['employment_type'] = df['employment_type'].map(employment_map)

In [10]:
remote_map = {
    0: 'Onsite',
    50: 'Hybrid',
    100: 'Remote'
}

df['work_mode'] = df['remote_ratio'].map(remote_map)

In [11]:
df['salary_in_usd'].mean()

np.float64(112297.86985172982)

In [12]:
df['job_title'].value_counts().head(10)

job_title
Data Scientist                143
Data Engineer                 132
Data Analyst                   97
Machine Learning Engineer      41
Research Scientist             16
Data Science Manager           12
Data Architect                 11
Machine Learning Scientist      8
Big Data Engineer               8
Director of Data Science        7
Name: count, dtype: int64

In [13]:
df['experience_level'].value_counts()

experience_level
Senior Level       280
Mid Level          213
Entry Level         88
Executive Level     26
Name: count, dtype: int64

In [14]:
df['company_size'].value_counts()

company_size
M    326
L    198
S     83
Name: count, dtype: int64

In [15]:
df['work_mode'].value_counts()

work_mode
Remote    381
Onsite    127
Hybrid     99
Name: count, dtype: int64

In [16]:
df.to_csv(
    'data_science_jobs_clean.csv',
    index=False
)

In [17]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size,work_mode
0,2020,Mid Level,Full Time,Data Scientist,70000,EUR,79833,DE,0,DE,L,Onsite
1,2020,Senior Level,Full Time,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S,Onsite
2,2020,Senior Level,Full Time,Big Data Engineer,85000,GBP,109024,GB,50,GB,M,Hybrid
3,2020,Mid Level,Full Time,Product Data Analyst,20000,USD,20000,HN,0,HN,S,Onsite
4,2020,Senior Level,Full Time,Machine Learning Engineer,150000,USD,150000,US,50,US,L,Hybrid

In [18]:
df['salary_in_usd'].mean()

np.float64(112297.86985172982)

In [19]:
df['job_title'].value_counts().head(10)

job_title
Data Scientist                143
Data Engineer                 132
Data Analyst                   97
Machine Learning Engineer      41
Research Scientist             16
Data Science Manager           12
Data Architect                 11
Machine Learning Scientist      8
Big Data Engineer               8
Director of Data Science        7
Name: count, dtype: int64

In [20]:
df.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False)

experience_level
Executive Level    199392.038462
Senior Level       138617.292857
Mid Level           87996.056338
Entry Level         61643.318182
Name: salary_in_usd, dtype: float64

In [21]:
df.groupby('work_mode')['salary_in_usd'].mean().sort_values(ascending=False)

work_mode
Remote    122457.454068
Onsite    106354.622047
Hybrid     80823.030303
Name: salary_in_usd, dtype: float64

In [22]:
df['work_mode'].value_counts()

work_mode
Remote    381
Onsite    127
Hybrid     99
Name: count, dtype: int64

In [23]:
df.groupby('company_size')['salary_in_usd'].mean().sort_values(ascending=False)

company_size
L    119242.994949
M    116905.466258
S     77632.674699
Name: salary_in_usd, dtype: float64

In [24]:
df.to_csv(
    'data_science_jobs_clean.csv',
    index=False
)